"""initial_schema_16_tables

Revision ID: cda7bb67f90a
Revises: 
Create Date: 2026-03-05 11:42:25.818263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cda7bb67f90a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.Enum('student', 'teacher', 'admin', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nivel_autoridad', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('permisos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=False),
    sa.Column('registro_id', sa.Text(), nullable=True),
    sa.Column('valor_anterior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valor_nuevo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origen', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('programada', 'en_curso', 'finalizada', 'cancelada', name='estadosesionenum'), nullable=True),
    sa.Column('url_sala', sa.Text(), nullable=True),
    sa.Column('url_grabacion', sa.Text(), nullable=True),
    sa.Column('tema_clase', sa.String(length=200), nullable=True),
    sa.Column('notas_profesor', sa.Text(), nullable=True),
    sa.Column('valoracion_alumno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nivel_mcer_actual', sa.String(length=2), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=True),
    sa.Column('idioma_objetivo', sa.String(length=50), nullable=False),
    sa.Column('idioma_nativo', sa.String(length=50), nullable=False),
    sa.Column('intereses_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('racha_dias', sa.Integer(), nullable=True),
    sa.Column('fecha_ultima_actividad', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('rating_promedio', sa.Float(), nullable=True),
    sa.Column('total_clases', sa.Integer(), nullable=True),
    sa.Column('disponibilidad_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tarifa_hora', sa.Float(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('publicada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['learning_levels.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_skill_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('habilidad', sa.Enum('listening', 'speaking', 'reading', 'writing', 'grammar', 'vocabulary', name='habilidadenum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('tendencia', sa.Enum('mejorando', 'estable', 'empeorando', name='tendenciaenum'), nullable=True),
    sa.Column('total_evaluaciones', sa.Integer(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_scores_user_id'), 'user_skill_scores', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('video', 'pdf', 'quiz', 'audio', 'ejercicio', name='tipomaterialenum'), nullable=False),
    sa.Column('url_recurso', sa.Text(), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('dificultad', sa.Integer(), nullable=True),
    sa.Column('vistas_totales', sa.Integer(), nullable=True),
    sa.Column('rating_promedio', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whiteboard_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('guardado_por', sa.UUID(), nullable=False),
    sa.Column('guardado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guardado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('material_id_rec', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('aceptada', sa.Boolean(), nullable=True),
    sa.Column('score_confianza', sa.Float(), nullable=False),
    sa.Column('algoritmo_usado', sa.String(length=50), nullable=False),
    sa.Column('resultado_post', sa.Enum('mejoro', 'igual', 'empeoro', name='resultadopostenum'), nullable=True),
    sa.Column('generada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('respondida_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id_rec'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_user_id'), 'ai_recommendations', ['user_id'], unique=False)
    op.create_table('content_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('tag_type', sa.Enum('habilidad', 'categoria', 'nivel', 'tema', 'contexto', name='tagtypeenum'), nullable=False),
    sa.Column('tag_value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('tiempo_segundos', sa.Integer(), nullable=True),
    sa.Column('completitud_pct', sa.Float(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('ultima_posicion', sa.Integer(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_logs_material_id'), 'learning_logs', ['material_id'], unique=False)
    op.create_index(op.f('ix_learning_logs_user_id'), 'learning_logs', ['user_id'], unique=False)
    op.create_table('quiz_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('puntuacion', sa.Float(), nullable=False),
    sa.Column('preguntas_total', sa.Integer(), nullable=False),
    sa.Column('respuestas_correctas', sa.Integer(), nullable=False),
    sa.Column('tiempo_total_seg', sa.Integer(), nullable=True),
    sa.Column('intento_numero', sa.Integer(), nullable=True),
    sa.Column('realizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_results_user_id'), 'quiz_results', ['user_id'], unique=False)
    op.create_table('quiz_error_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_result_id', sa.UUID(), nullable=False),
    sa.Column('tipo_error', sa.Enum('sintaxis', 'vocabulario', 'pronunciacion', 'comprension', 'tiempo_verbal', name='tipoerrorenum'), nullable=False),
    sa.Column('frecuencia', sa.Integer(), nullable=False),
    sa.Column('ejemplos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['quiz_result_id'], ['quiz_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_error_details')
    op.drop_index(op.f('ix_quiz_results_user_id'), table_name='quiz_results')
    op.drop_table('quiz_results')
    op.drop_index(op.f('ix_learning_logs_user_id'), table_name='learning_logs')
    op.drop_index(op.f('ix_learning_logs_material_id'), table_name='learning_logs')
    op.drop_table('learning_logs')
    op.drop_table('content_tags')
    op.drop_index(op.f('ix_ai_recommendations_user_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_table('whiteboard_sessions')
    op.drop_table('materials')
    op.drop_index(op.f('ix_user_skill_scores_user_id'), table_name='user_skill_scores')
    op.drop_table('user_skill_scores')
    op.drop_table('units')
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    op.drop_table('live_sessions')
    op.drop_table('audit_logs')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('learning_levels')
    # ### end Alembic commands ###
